[package]
name = "clic"
version = "0.1.0"
authors = ["Michal Jabczyk <michal@jabczyk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meval = "0.2"
rustyline = "8.0.0"
directories = "3.0.1"

